import type { SimEvent } from '../game/events';

/**
 * The game's voice. It subscribes to the event list and nothing else.
 *
 * It never reads RunState, imports no sim module other than events.ts, and holds
 * no game rules: the events carry values for exactly this reason, so a sound is
 * a lookup from what the sim already said rather than a second place the rules
 * are written down. src/__tests__/boundary.test.ts holds that shut, narrowed
 * to this one file, because a folder rule over src/app would be the wrong
 * instrument and a comment asking nicely would be no instrument at all.
 *
 * Five clips, and the coverage is the point rather than the count. An earlier
 * shape shipped two, and both landed on the two commonest events in the game
 * while the scarcest objects stayed silent: a drop sounded exactly like a corpse
 * and the belch, which the whole feast set piece is built around, made no noise.
 * Touhou's Mountain of Faith bank is the shape copied here, an item and a
 * power-up alongside a damage sound and a death.
 */

/**
 * Where a clip comes out: the one call the voice makes of the effects channel.
 * Named for what the voice needs rather than for the class that satisfies it,
 * so this module reaches nothing outside the event list.
 */
interface SoundOutput {
  play(alias: string, options: { volume: number }): void;
}

// The synthesized placeholders, generated by scripts/make-sounds.mjs.
const CLIPS = {
  swallow: 'main/sounds/sfx-swallow.wav',
  treasure: 'main/sounds/sfx-treasure.wav',
  toll: 'main/sounds/sfx-toll.wav',
  hit: 'main/sounds/sfx-hit.wav',
  eruption: 'main/sounds/sfx-eruption.wav',
} as const;

// How loud each clip plays relative to the effects volume the player set.
const LEVELS: Record<keyof typeof CLIPS, number> = {
  swallow: 0.5,
  treasure: 0.7,
  toll: 0.55,
  hit: 0.8,
  eruption: 1,
};

/**
 * Which clip an event asks for, or null for the events that make no sound.
 *
 * The drop's own chime is chosen from the kind the chimed event already carries,
 * so telling treasure from a corpse needs no game rule here and no new event.
 */
const clipFor = (event: SimEvent): keyof typeof CLIPS | null => {
  if (event.type === 'chimed') {
    return event.kind === 'drop' ? 'treasure' : 'swallow';
  }
  if (event.type === 'tolled') return 'toll';
  if (event.type === 'graveHit') return 'hit';
  if (event.type === 'belched') return 'eruption';
  return null;
};

// Once per session, because playFor runs on every event a run emits and
// whatever stopped the first clip is not fixed by the time of the next one.
let reportedSilence = false;

// Says that a sound was lost, because nothing abnormal is silent.
const reportSilence = (clip: keyof typeof CLIPS, error: unknown): void => {
  if (reportedSilence) return;
  reportedSilence = true;
  console.warn(
    `the ${clip} sound would not play; the run carries on in silence and no later sound failure is reported`,
    error,
  );
};

/**
 * Plays whatever this event sounds like.
 *
 * A clip that will not play is swallowed rather than thrown, because sound is
 * the one subsystem whose failure must never take the run with it.
 *
 * A clip still loading is not the case this catches, and a cold boot cannot
 * reach it: the navigation awaits a screen's asset bundle before the screen
 * exists, and every clip above sits in the bundle the sounding screens declare,
 * which src/app/__tests__/sound.test.ts holds shut. So what reaches the catch
 * is an alias no bundle registers or a playback that genuinely failed, and both
 * of those are abnormal, which is why one of them says so.
 */
const playFor = (output: SoundOutput, event: SimEvent): void => {
  const clip = clipFor(event);
  if (clip === null) return;
  try {
    output.play(CLIPS[clip], { volume: LEVELS[clip] });
  } catch (error) {
    reportSilence(clip, error);
    return;
  }
};

/**
 * Unlocks the audio context on the first real user gesture.
 *
 * Browser autoplay policy blocks audio before a gesture, and the boot already
 * logs three warnings about it. The first gesture in this game is RISE on the
 * title screen, which is where this is called.
 *
 * The package is reached through a dynamic import rather than at module scope,
 * because @pixi/sound probes `document` for format support the moment it is
 * evaluated, and this module is on the import path of every screen test that
 * runs under node.
 */
const primeSound = (): void => {
  void import('@pixi/sound')
    .then(({ sound }) => sound.context.audioContext.resume())
    .catch(() => undefined);
};

export { clipFor, playFor, primeSound };
